openapi: 3.0.0
info:
  title: API Auth
  version: 1.0.0
paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Registro de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        '201':
          description: Usuário criado
  /auth/login:
    post:
      tags: [Auth]
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Retorna JWT
  /auth/logout:
    post:
      tags: [Auth]
      summary: Logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout realizado
  /protected/me:
    get:
      tags: [Protected]
      summary: Dados do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Retorna user
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT